//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 01:15:02 AM WEST 
//


package xml.meta;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for cube complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cube">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="factTable">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;choice>
 *                     &lt;element name="fact" type="{}fact"/>
 *                     &lt;element name="derivedFact" type="{}derived"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *                 &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="preaggregates">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="preaggregate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="granularity">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                                       &lt;element name="dimension">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                                                 &lt;element name="level">
 *                                                   &lt;complexType>
 *                                                     &lt;simpleContent>
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                         &lt;attribute name="levelID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                       &lt;/extension>
 *                                                     &lt;/simpleContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="facts">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                                       &lt;element name="fact">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="aggregation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="factID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cubeDimensions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="dimension">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="dimID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cube", propOrder = {
    "factTable",
    "preaggregates",
    "cubeDimensions"
})
public class Cube implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

    @XmlElement(required = true)
    protected Cube.FactTable factTable;
    @XmlElement(required = true)
    protected Cube.Preaggregates preaggregates;
    @XmlElement(required = true)
    protected Cube.CubeDimensions cubeDimensions;

    /**
     * Gets the value of the factTable property.
     * 
     * @return
     *     possible object is
     *     {@link Cube.FactTable }
     *     
     */
    public Cube.FactTable getFactTable() {
        return factTable;
    }

    /**
     * Sets the value of the factTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cube.FactTable }
     *     
     */
    public void setFactTable(Cube.FactTable value) {
        this.factTable = value;
    }

    /**
     * Gets the value of the preaggregates property.
     * 
     * @return
     *     possible object is
     *     {@link Cube.Preaggregates }
     *     
     */
    public Cube.Preaggregates getPreaggregates() {
        return preaggregates;
    }

    /**
     * Sets the value of the preaggregates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cube.Preaggregates }
     *     
     */
    public void setPreaggregates(Cube.Preaggregates value) {
        this.preaggregates = value;
    }

    /**
     * Gets the value of the cubeDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link Cube.CubeDimensions }
     *     
     */
    public Cube.CubeDimensions getCubeDimensions() {
        return cubeDimensions;
    }

    /**
     * Sets the value of the cubeDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cube.CubeDimensions }
     *     
     */
    public void setCubeDimensions(Cube.CubeDimensions value) {
        this.cubeDimensions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="dimension">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="dimID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dimension"
    })
    public static class CubeDimensions implements Serializable{

        /**
    	 * 
    	 */
    	private static final long serialVersionUID = 1L;

        @XmlElement(required = true)
        protected List<Cube.CubeDimensions.Dimension> dimension;

        /**
         * Gets the value of the dimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDimension().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Cube.CubeDimensions.Dimension }
         * 
         * 
         */
        public List<Cube.CubeDimensions.Dimension> getDimension() {
            if (dimension == null) {
                dimension = new ArrayList<Cube.CubeDimensions.Dimension>();
            }
            return this.dimension;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="dimID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        
        public static class Dimension implements Serializable{

            /**
        	 * 
        	 */
        	private static final long serialVersionUID = 1L;

            @XmlValue
            protected String value;
            @XmlAttribute
            protected String displayName;
            @XmlAttribute
            protected String dimID;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the displayName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayName() {
                return displayName;
            }

            /**
             * Sets the value of the displayName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayName(String value) {
                this.displayName = value;
            }

            /**
             * Gets the value of the dimID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDimID() {
                return dimID;
            }

            /**
             * Sets the value of the dimID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDimID(String value) {
                this.dimID = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;choice>
     *           &lt;element name="fact" type="{}fact"/>
     *           &lt;element name="derivedFact" type="{}derived"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *       &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "factOrDerivedFact"
    })
    public static class FactTable implements Serializable{

        /**
    	 * 
    	 */
    	private static final long serialVersionUID = 1L;

        @XmlElements({
            @XmlElement(name = "fact", type = xml.meta.Fact.class),
            @XmlElement(name = "derivedFact", type = Derived.class)
        })
        protected List<Object> factOrDerivedFact;
        @XmlAttribute
        protected String tableID;
        @XmlAttribute
        protected String displayName;

        /**
         * Gets the value of the factOrDerivedFact property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the factOrDerivedFact property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFactOrDerivedFact().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link xml.meta.Fact }
         * {@link Derived }
         * 
         * 
         */
        public List<Object> getFactOrDerivedFact() {
            if (factOrDerivedFact == null) {
                factOrDerivedFact = new ArrayList<Object>();
            }
            return this.factOrDerivedFact;
        }

        /**
         * Gets the value of the tableID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTableID() {
            return tableID;
        }

        /**
         * Sets the value of the tableID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTableID(String value) {
            this.tableID = value;
        }

        /**
         * Gets the value of the displayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="preaggregate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="granularity">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                             &lt;element name="dimension">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                                       &lt;element name="level">
     *                                         &lt;complexType>
     *                                           &lt;simpleContent>
     *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                               &lt;attribute name="levelID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                             &lt;/extension>
     *                                           &lt;/simpleContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="facts">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                             &lt;element name="fact">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="aggregation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="factID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "preaggregate"
    })
    public static class Preaggregates implements Serializable{

        /**
    	 * 
    	 */
    	private static final long serialVersionUID = 1L;

    	@XmlElement(required = true)
        protected List<Cube.Preaggregates.Preaggregate> preaggregate;

        /**
         * Gets the value of the preaggregate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the preaggregate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPreaggregate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Cube.Preaggregates.Preaggregate }
         * 
         * 
         */
        public List<Cube.Preaggregates.Preaggregate> getPreaggregate() {
            if (preaggregate == null) {
                preaggregate = new ArrayList<Cube.Preaggregates.Preaggregate>();
            }
            return this.preaggregate;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="granularity">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *                   &lt;element name="dimension">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *                             &lt;element name="level">
         *                               &lt;complexType>
         *                                 &lt;simpleContent>
         *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                     &lt;attribute name="levelID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                   &lt;/extension>
         *                                 &lt;/simpleContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="facts">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *                   &lt;element name="fact">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="aggregation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="factID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "granularity",
            "facts"
        })
        
        public static class Preaggregate implements Serializable{

            /**
        	 * 
        	 */
        	private static final long serialVersionUID = 1L;

            @XmlElement(required = true)
            protected Cube.Preaggregates.Preaggregate.Granularity granularity;
            @XmlElement(required = true)
            protected Cube.Preaggregates.Preaggregate.Facts facts;
            @XmlAttribute
            protected String tableID;

            /**
             * Gets the value of the granularity property.
             * 
             * @return
             *     possible object is
             *     {@link Cube.Preaggregates.Preaggregate.Granularity }
             *     
             */
            public Cube.Preaggregates.Preaggregate.Granularity getGranularity() {
                return granularity;
            }

            /**
             * Sets the value of the granularity property.
             * 
             * @param value
             *     allowed object is
             *     {@link Cube.Preaggregates.Preaggregate.Granularity }
             *     
             */
            public void setGranularity(Cube.Preaggregates.Preaggregate.Granularity value) {
                this.granularity = value;
            }

            /**
             * Gets the value of the facts property.
             * 
             * @return
             *     possible object is
             *     {@link Cube.Preaggregates.Preaggregate.Facts }
             *     
             */
            public Cube.Preaggregates.Preaggregate.Facts getFacts() {
                return facts;
            }

            /**
             * Sets the value of the facts property.
             * 
             * @param value
             *     allowed object is
             *     {@link Cube.Preaggregates.Preaggregate.Facts }
             *     
             */
            public void setFacts(Cube.Preaggregates.Preaggregate.Facts value) {
                this.facts = value;
            }

            /**
             * Gets the value of the tableID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTableID() {
                return tableID;
            }

            /**
             * Sets the value of the tableID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTableID(String value) {
                this.tableID = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
             *         &lt;element name="fact">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="aggregation" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="factID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fact"
            })
            public static class Facts implements Serializable{

                /**
            	 * 
            	 */
            	private static final long serialVersionUID = 1L;

                protected List<Cube.Preaggregates.Preaggregate.Facts.Fact> fact;

                /**
                 * Gets the value of the fact property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the fact property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getFact().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Cube.Preaggregates.Preaggregate.Facts.Fact }
                 * 
                 * 
                 */
                public List<Cube.Preaggregates.Preaggregate.Facts.Fact> getFact() {
                    if (fact == null) {
                        fact = new ArrayList<Cube.Preaggregates.Preaggregate.Facts.Fact>();
                    }
                    return this.fact;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="aggregation" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="factID" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "aggregation"
                })
                public static class Fact implements Serializable{

                    /**
                	 * 
                	 */
                	private static final long serialVersionUID = 1L;

                    @XmlElement(required = true)
                    protected String aggregation;
                    @XmlAttribute
                    protected String factID;

                    /**
                     * Gets the value of the aggregation property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAggregation() {
                        return aggregation;
                    }

                    /**
                     * Sets the value of the aggregation property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAggregation(String value) {
                        this.aggregation = value;
                    }

                    /**
                     * Gets the value of the factID property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFactID() {
                        return factID;
                    }

                    /**
                     * Sets the value of the factID property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFactID(String value) {
                        this.factID = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
             *         &lt;element name="dimension">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
             *                   &lt;element name="level">
             *                     &lt;complexType>
             *                       &lt;simpleContent>
             *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                           &lt;attribute name="levelID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                         &lt;/extension>
             *                       &lt;/simpleContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dimension"
            })
            public static class Granularity implements Serializable{

                /**
            	 * 
            	 */
            	private static final long serialVersionUID = 1L;

                protected List<Cube.Preaggregates.Preaggregate.Granularity.Dimension> dimension;

                /**
                 * Gets the value of the dimension property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the dimension property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDimension().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Cube.Preaggregates.Preaggregate.Granularity.Dimension }
                 * 
                 * 
                 */
                public List<Cube.Preaggregates.Preaggregate.Granularity.Dimension> getDimension() {
                    if (dimension == null) {
                        dimension = new ArrayList<Cube.Preaggregates.Preaggregate.Granularity.Dimension>();
                    }
                    return this.dimension;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
                 *         &lt;element name="level">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="levelID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="tableID" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "level"
                })
                public static class Dimension implements Serializable{

                    /**
                	 * 
                	 */
                	private static final long serialVersionUID = 1L;

                    protected List<Cube.Preaggregates.Preaggregate.Granularity.Dimension.Level> level;
                    @XmlAttribute
                    protected String tableID;

                    /**
                     * Gets the value of the level property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the level property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getLevel().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Cube.Preaggregates.Preaggregate.Granularity.Dimension.Level }
                     * 
                     * 
                     */
                    public List<Cube.Preaggregates.Preaggregate.Granularity.Dimension.Level> getLevel() {
                        if (level == null) {
                            level = new ArrayList<Cube.Preaggregates.Preaggregate.Granularity.Dimension.Level>();
                        }
                        return this.level;
                    }

                    /**
                     * Gets the value of the tableID property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTableID() {
                        return tableID;
                    }

                    /**
                     * Sets the value of the tableID property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTableID(String value) {
                        this.tableID = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="levelID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Level implements Serializable{

                        /**
                    	 * 
                    	 */
                    	private static final long serialVersionUID = 1L;

                        @XmlValue
                        protected String value;
                        @XmlAttribute
                        @XmlSchemaType(name = "anySimpleType")
                        protected String levelID;

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the levelID property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLevelID() {
                            return levelID;
                        }

                        /**
                         * Sets the value of the levelID property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLevelID(String value) {
                            this.levelID = value;
                        }

                    }

                }

            }

        }

    }

}
