//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 01:15:02 AM WEST 
//


package xml.meta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.meta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Metamodel_QNAME = new QName("", "metamodel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.meta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cube.Preaggregates.Preaggregate.Granularity }
     * 
     */
    public Cube.Preaggregates.Preaggregate.Granularity createCubePreaggregatesPreaggregateGranularity() {
        return new Cube.Preaggregates.Preaggregate.Granularity();
    }

    /**
     * Create an instance of {@link Derived.Aggregation }
     * 
     */
    public Derived.Aggregation createDerivedAggregation() {
        return new Derived.Aggregation();
    }

    /**
     * Create an instance of {@link Cube.Preaggregates.Preaggregate.Facts.Fact }
     * 
     */
    public Cube.Preaggregates.Preaggregate.Facts.Fact createCubePreaggregatesPreaggregateFactsFact() {
        return new Cube.Preaggregates.Preaggregate.Facts.Fact();
    }

    /**
     * Create an instance of {@link xml.meta.Level.UpperLevel }
     * 
     */
    public xml.meta.Level.UpperLevel createLevelUpperLevel() {
        return new xml.meta.Level.UpperLevel();
    }

    /**
     * Create an instance of {@link Databases }
     * 
     */
    public Databases createDatabases() {
        return new Databases();
    }

    /**
     * Create an instance of {@link Table.PrimaryKey.Attribute }
     * 
     */
    public Table.PrimaryKey.Attribute createTablePrimaryKeyAttribute() {
        return new Table.PrimaryKey.Attribute();
    }

    /**
     * Create an instance of {@link Derived.AdditionDimensions.Dimension }
     * 
     */
    public Derived.AdditionDimensions.Dimension createDerivedAdditionDimensionsDimension() {
        return new Derived.AdditionDimensions.Dimension();
    }

    /**
     * Create an instance of {@link LevelRef }
     * 
     */
    public LevelRef createLevelRef() {
        return new LevelRef();
    }

    /**
     * Create an instance of {@link LevelAttribute }
     * 
     */
    public LevelAttribute createLevelAttribute() {
        return new LevelAttribute();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link xml.meta.Level.Attributes }
     * 
     */
    public xml.meta.Level.Attributes createLevelAttributes() {
        return new xml.meta.Level.Attributes();
    }

    /**
     * Create an instance of {@link Table.PrimaryKey }
     * 
     */
    public Table.PrimaryKey createTablePrimaryKey() {
        return new Table.PrimaryKey();
    }

    /**
     * Create an instance of {@link Table.ForeignKeys.ForeignKey }
     * 
     */
    public Table.ForeignKeys.ForeignKey createTableForeignKeysForeignKey() {
        return new Table.ForeignKeys.ForeignKey();
    }

    /**
     * Create an instance of {@link xml.meta.Level }
     * 
     */
    public xml.meta.Level createLevel() {
        return new xml.meta.Level();
    }

    /**
     * Create an instance of {@link xml.meta.Fact.Aggregation }
     * 
     */
    public xml.meta.Fact.Aggregation createFactAggregation() {
        return new xml.meta.Fact.Aggregation();
    }

    /**
     * Create an instance of {@link Derived }
     * 
     */
    public Derived createDerived() {
        return new Derived();
    }

    /**
     * Create an instance of {@link Table.Attributes }
     * 
     */
    public Table.Attributes createTableAttributes() {
        return new Table.Attributes();
    }

    /**
     * Create an instance of {@link xml.meta.Fact.AdditionDimensions }
     * 
     */
    public xml.meta.Fact.AdditionDimensions createFactAdditionDimensions() {
        return new xml.meta.Fact.AdditionDimensions();
    }

    /**
     * Create an instance of {@link Table.ForeignKeys.ForeignKey.Attribute }
     * 
     */
    public Table.ForeignKeys.ForeignKey.Attribute createTableForeignKeysForeignKeyAttribute() {
        return new Table.ForeignKeys.ForeignKey.Attribute();
    }

    /**
     * Create an instance of {@link xml.meta.Fact }
     * 
     */
    public xml.meta.Fact createFact() {
        return new xml.meta.Fact();
    }

    /**
     * Create an instance of {@link xml.meta.Level.LowerLevel }
     * 
     */
    public xml.meta.Level.LowerLevel createLevelLowerLevel() {
        return new xml.meta.Level.LowerLevel();
    }

    /**
     * Create an instance of {@link Cube.Preaggregates.Preaggregate }
     * 
     */
    public Cube.Preaggregates.Preaggregate createCubePreaggregatesPreaggregate() {
        return new Cube.Preaggregates.Preaggregate();
    }

    /**
     * Create an instance of {@link Snowflaked }
     * 
     */
    public Snowflaked createSnowflaked() {
        return new Snowflaked();
    }

    /**
     * Create an instance of {@link MetaModel.Cubes }
     * 
     */
    public MetaModel.Cubes createMetaModelCubes() {
        return new MetaModel.Cubes();
    }

    /**
     * Create an instance of {@link xml.meta.Dimension }
     * 
     */
    public xml.meta.Dimension createDimension() {
        return new xml.meta.Dimension();
    }

    /**
     * Create an instance of {@link Cube.Preaggregates.Preaggregate.Facts }
     * 
     */
    public Cube.Preaggregates.Preaggregate.Facts createCubePreaggregatesPreaggregateFacts() {
        return new Cube.Preaggregates.Preaggregate.Facts();
    }

    /**
     * Create an instance of {@link Databases.Database }
     * 
     */
    public Databases.Database createDatabasesDatabase() {
        return new Databases.Database();
    }

    /**
     * Create an instance of {@link xml.meta.Dimension.Hierarchies }
     * 
     */
    public xml.meta.Dimension.Hierarchies createDimensionHierarchies() {
        return new xml.meta.Dimension.Hierarchies();
    }

    /**
     * Create an instance of {@link Table.ForeignKeys }
     * 
     */
    public Table.ForeignKeys createTableForeignKeys() {
        return new Table.ForeignKeys();
    }

    /**
     * Create an instance of {@link Derived.AdditionDimensions }
     * 
     */
    public Derived.AdditionDimensions createDerivedAdditionDimensions() {
        return new Derived.AdditionDimensions();
    }

    /**
     * Create an instance of {@link TableAttribute }
     * 
     */
    public TableAttribute createTableAttribute() {
        return new TableAttribute();
    }

    /**
     * Create an instance of {@link Cube.CubeDimensions.Dimension }
     * 
     */
    public Cube.CubeDimensions.Dimension createCubeCubeDimensionsDimension() {
        return new Cube.CubeDimensions.Dimension();
    }

    /**
     * Create an instance of {@link Cube.Preaggregates }
     * 
     */
    public Cube.Preaggregates createCubePreaggregates() {
        return new Cube.Preaggregates();
    }

    /**
     * Create an instance of {@link xml.meta.Dimension.Hierarchies.Hierarchy }
     * 
     */
    public xml.meta.Dimension.Hierarchies.Hierarchy createDimensionHierarchiesHierarchy() {
        return new xml.meta.Dimension.Hierarchies.Hierarchy();
    }

    /**
     * Create an instance of {@link xml.meta.Fact.AdditionDimensions.Dimension }
     * 
     */
    public xml.meta.Fact.AdditionDimensions.Dimension createFactAdditionDimensionsDimension() {
        return new xml.meta.Fact.AdditionDimensions.Dimension();
    }

    /**
     * Create an instance of {@link xml.meta.Dimension.Levels }
     * 
     */
    public xml.meta.Dimension.Levels createDimensionLevels() {
        return new xml.meta.Dimension.Levels();
    }

    /**
     * Create an instance of {@link Cube.CubeDimensions }
     * 
     */
    public Cube.CubeDimensions createCubeCubeDimensions() {
        return new Cube.CubeDimensions();
    }

    /**
     * Create an instance of {@link Cube.Preaggregates.Preaggregate.Granularity.Dimension }
     * 
     */
    public Cube.Preaggregates.Preaggregate.Granularity.Dimension createCubePreaggregatesPreaggregateGranularityDimension() {
        return new Cube.Preaggregates.Preaggregate.Granularity.Dimension();
    }

    /**
     * Create an instance of {@link Cube }
     * 
     */
    public Cube createCube() {
        return new Cube();
    }

    /**
     * Create an instance of {@link MetaModel.Dimensions }
     * 
     */
    public MetaModel.Dimensions createMetaModelDimensions() {
        return new MetaModel.Dimensions();
    }

    /**
     * Create an instance of {@link MetaModel.Tables }
     * 
     */
    public MetaModel.Tables createMetaModelTables() {
        return new MetaModel.Tables();
    }

    /**
     * Create an instance of {@link Cube.Preaggregates.Preaggregate.Granularity.Dimension.Level }
     * 
     */
    public Cube.Preaggregates.Preaggregate.Granularity.Dimension.Level createCubePreaggregatesPreaggregateGranularityDimensionLevel() {
        return new Cube.Preaggregates.Preaggregate.Granularity.Dimension.Level();
    }

    /**
     * Create an instance of {@link Cube.FactTable }
     * 
     */
    public Cube.FactTable createCubeFactTable() {
        return new Cube.FactTable();
    }

    /**
     * Create an instance of {@link xml.meta.Dimension.Hierarchies.Hierarchy.Level }
     * 
     */
    public xml.meta.Dimension.Hierarchies.Hierarchy.Level createDimensionHierarchiesHierarchyLevel() {
        return new xml.meta.Dimension.Hierarchies.Hierarchy.Level();
    }

    /**
     * Create an instance of {@link MetaModel }
     * 
     */
    public MetaModel createMetaModel() {
        return new MetaModel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "metamodel")
    public JAXBElement<MetaModel> createMetamodel(MetaModel value) {
        return new JAXBElement<MetaModel>(_Metamodel_QNAME, MetaModel.class, null, value);
    }

}
