//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 01:15:02 AM WEST 
//


package xml.meta;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for snowflaked complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="snowflaked">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="snowflaked" type="{}snowflaked"/>
 *         &lt;element name="attr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *       &lt;attribute name="fkey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ftable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ftablepk" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "snowflaked", propOrder = {
    "snowflaked",
    "attr"
})
public class Snowflaked implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

    protected Snowflaked snowflaked;
    protected String attr;
    @XmlAttribute
    protected String fkey;
    @XmlAttribute
    protected String ftable;
    @XmlAttribute
    protected String ftablepk;

    /**
     * Gets the value of the snowflaked property.
     * 
     * @return
     *     possible object is
     *     {@link Snowflaked }
     *     
     */
    public Snowflaked getSnowflaked() {
        return snowflaked;
    }

    /**
     * Sets the value of the snowflaked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Snowflaked }
     *     
     */
    public void setSnowflaked(Snowflaked value) {
        this.snowflaked = value;
    }

    /**
     * Gets the value of the attr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttr() {
        return attr;
    }

    /**
     * Sets the value of the attr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttr(String value) {
        this.attr = value;
    }

    /**
     * Gets the value of the fkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkey() {
        return fkey;
    }

    /**
     * Sets the value of the fkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkey(String value) {
        this.fkey = value;
    }

    /**
     * Gets the value of the ftable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFtable() {
        return ftable;
    }

    /**
     * Sets the value of the ftable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFtable(String value) {
        this.ftable = value;
    }

    /**
     * Gets the value of the ftablepk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFtablepk() {
        return ftablepk;
    }

    /**
     * Sets the value of the ftablepk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFtablepk(String value) {
        this.ftablepk = value;
    }

}
